import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import QRCTXProvider from "@/context/qr-contex";
import Header from "@/components/header";
import { ThemeProvider } from "next-themes";
import { ThemeSwitch } from "@/components/toggle-theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QR Generator | Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <Header />
          <ThemeSwitch />
          <QRCTXProvider>{children}</QRCTXProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
